services:
  grafana:
    user: root
    container_name: 'red-hat-insights'

    build:
      context: ./.config
      args:
        grafana_image: ${GRAFANA_IMAGE:-grafana-enterprise}
        grafana_version: ${GRAFANA_VERSION:-11.2.0}
        development: ${DEVELOPMENT:-false}
    ports:
      - 3000:3000/tcp
    volumes:
      - ./dist:/var/lib/grafana/plugins/red-hat-insights
      - ./provisioning:/etc/grafana/provisioning
      - .:/root/red-hat-insights

    environment:
      NODE_ENV: development
      GF_LOG_FILTERS: plugin.red-hat-insights:debug
      GF_LOG_LEVEL: debug
      GF_DATAPROXY_LOGGING: 1
      GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS: red-hat-insights
